### ISSUE TITLE
Data Preparation

### ISSUE THREAD

**Issue by benchuCumt** [MingLunHan/CIF-HieraDist#3]
作者你好，我在准备数据的时候遇到了问题
![image](https://github.com/MingLunHan/CIF-HieraDist/assets/73736249/1c2d63ad-9ae8-4c4e-b136-5538d69f7d75)
我下载的sishell_1数据集中并没有该子文件夹，请问是要对原数据集进行某种处理吗？
![image](https://github.com/MingLunHan/CIF-HieraDist/assets/73736249/dfa8ed26-ab5e-449c-b098-d4c5655e19ee)

**Comment by MingLunHan** [comment]
@123go-maker 你好，我观察到 dump/raw 是从 SpeedPerturbatedAISHELL1 中所需的字段。我的实验中没使用speed perturbation。

```
dataset = AISHELL1(input_root.as_posix(), split=split)
# dataset = SpeedPerturbatedAISHELL1(input_root.as_posix(), split=split)
```

建议使用 Class AISHELL1 进行数据处理，而不是SpeedPerturbatedAISHELL1。

你的报错是因为使用 SpeedPerturbatedAISHELL1 的话需要自己事先将speed pertubated 的数据准备好。

**Comment by MingLunHan** [comment]
@123go-maker 你好，请问你是否解决该问题，是否还有其他问题。如果没有问题的话，我将关闭该issue。

**Comment by benchuCumt** [comment]
好的谢谢您
